export const expectedSeleniumItems = [
  "SELENIUM WITH JAVA TUTORIAL",
  "SELENIUM WITH PYTHON TUTORIAL",
  "TESTNG INTEGRATION WITH SELENIUM",
  "SELENIUM IDE: COMPLETE TUTORIAL",
  "* PRACTICE *",
  "25+ SELENIUM COMMANDS CHEATSHEET",
  "10 DEMO WEBSITES FOR PRACTICE",
  "14 SELENIUM CODING EXERCISES",
  "* ADVANCED TRENDS *",
  "AI AND ML IN SELENIUM TESTING",
  "(BDD)SELENIUM AND CUCUMBER INTEGRATION",
  "AUTOMATE REST APIS WITH SELENIUM",
  "PERFORM VISUAL TESTING WITH SELENIUM",
  "DATA DRIVEN TESTING WITH SELENIUM",
  "ALL ADVANCED SELENIUM CONCEPTS",
  "VIEW ALL BLOGS",
  "Selenium with Java Tutorial ",
  "Selenium with Python Tutorial",
  "TestNG Integration with Selenium",
  "Selenium IDE: Complete Tutorial",
  "* Practice *",
  "25+ Selenium Commands Cheatsheet",
  "10 Demo Websites for Practice",
  "10 Demo Websites for Practice",
  "14 Selenium Coding Exercises",
  "* Advanced Trends *",
  "AI and ML in Selenium Testing",
  "(BDD)Selenium and Cucumber Integration",
  "Automate REST APIs with Selenium",
  "Perform Visual Testing with Selenium",
  "Data Driven Testing with Selenium",
  "All Advanced Selenium Concepts",
  "View All Blogs",
];
